name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t nextjs-app:${{ github.sha }} .
          docker tag nextjs-app:${{ github.sha }} saiansuri/nextjs-app:${{ github.sha }}  
          
      - name: Push Docker Image to Docker Hub
        run: |
          docker push saiansuri/nextjs-app:${{ github.sha }}

  deploy:
    name: Deploy to EKS
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name Nextjs-app --region us-east-1

      - name: Set the latest image in Kubernetes
        run: |
          kubectl set image deployment/nextjs-deployment nextjs-app=saiansuri/nextjs-app:${{ github.sha }}

